### ISSUE TITLE
TypeError: ref.save is not a function

### ISSUE THREAD

**Issue by kolaloko** [zappajs/zappajs#125]
I'm getting an error this error after I upgraded zappajs from 5.2.0 to 6.0.2 or higher.
The error occurs after client connection via socket.io. Should I change something before the upgrade?

```
/home/kola/server/node_modules/zappajs/lib/io-session.js:153
           return (ref = ctx.session) != null ? ref.save() : void 0;
                                                    ^

TypeError: ref.save is not a function
    at /home/kola/server/node_modules/zappajs/lib/io-session.js:153:52
    at get_session (/home/kola/server/node_modules/zappajs/lib/io-session.js:126:9)
    at /home/kola/server/node_modules/zappajs/lib/io-session.js:144:14
    at /home/kola/server/node_modules/zappajs/lib/zappa.js:300:18
    at /home/kola/server/node_modules/zappajs/lib/zappa.js:607:20
    at Namespace.<anonymous> (/home/kola/server/node_modules/zappajs/lib/zappa.js:629:50)
    at emitOne (events.js:82:20)
    at Namespace.emit (events.js:169:7)
    at Namespace.emit (/home/kola/server/node_modules/socket.io/lib/namespace.js:209:10)
    at /home/kola/server/node_modules/socket.io/lib/namespace.js:177:14
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

**Comment by shimaore** [comment]
How do you create the session object used by ZappaJS?
And do you register that session object with `@use session: ` ?

**Comment by kolaloko** [comment]
```
ExpressRedisStore = require('connect-redis') @session
@sessionStore = new ExpressRedisStore(
    host: redisUrl.host
    port: redisUrl.port
    pass: redisUrl.password
    db: redisUrl.database
    ttl: ttlTime
)
@use session:
    store: @sessionStore
    maxAge: age
    secret: sessionSecret
    cookie:
        maxAge: age
        secure: true
    resave: true
    saveUninitialized: false
    name: name
```

**Comment by shimaore** [comment]
If you run the server with `DEBUG=zappajs:io-session` in the environment you might get some indication of what went wrong.

Is the problem still present if you use the latest version (6.3.0)?

**Comment by kolaloko** [comment]
The problem is still present in the latest version (6.4.0)

`DEBUG =zappajs:io-session,socket.io:*`

```
14:07:57 socket.io:server incoming connection with id k7mauPCnPtYJlP-7AAAA
14:07:57 socket.io:client connecting to namespace /
14:07:57 socket.io:namespace adding socket to nsp /
14:07:57 socket.io:client writing packet {"type":4,"data":"AuthorizationFailed","nsp":"/"}
14:08:01 socket.io:server incoming connection with id JDInI651NHFhnvKhAAAB
14:08:01 socket.io:client connecting to namespace /
14:08:01 socket.io:namespace adding socket to nsp /
14:08:01 socket.io:socket socket connected - writing packet
14:08:01 socket.io:socket joining room JDInI651NHFhnvKhAAAB
14:08:01 socket.io:client writing packet {"type":0,"nsp":"/"}
14:08:01 socket.io:socket joining room 588b405bae62e75793f563d9
14:08:01 /srv/home/stephane/Artisan/Managed/Node/zappajs/src/io-session.coffee.md:154
return (ref = ctx.session) != null ? ref.save() : void 0;
^
TypeError: ref.save is not a function
at /home/kola/server/node_modules/zappajs/lib/io-session.js:154:52
at get_session (/home/kola/server/node_modules/zappajs/lib/io-session.js:127:9)
at /home/kola/server/node_modules/zappajs/lib/io-session.js:145:14
at /home/kola/server/node_modules/zappajs/lib/zappa.js:329:18
at /home/kola/server/node_modules/zappajs/lib/zappa.js:636:20
at Namespace.<anonymous> (/home/kola/server/node_modules/zappajs/lib/zappa.js:658:50)
at emitOne (events.js:82:20)
at Namespace.emit (events.js:169:7)
at Namespace.emit (/home/kola/server/node_modules/socket.io/lib/namespace.js:209:10)
at /home/kola/server/node_modules/socket.io/lib/namespace.js:177:14
at nextTickCallbackWith0Args (node.js:489:9)
at process._tickDomainCallback (node.js:459:13)
```

Do you have any suggestion? Thank you.

**Comment by shimaore** [comment]
@kolaloko Any chance you might accidentally be modifying `@session` inside one of your socket.io handlers? In other words, you might have code that does:
```
@on 'my-message', ->
  @session = something
```
instead of
```
@on 'my-message', ->
  @session.my_data = something
```

Another quick check: you might want to check what version of expression-session you are using as well in case an older version isn't implementing the `Session` object the same way, although since you tested with a recent zappajs copy I expect you should be using the latest one already:
```
$ npm ls | grep express-session
├─┬ express-session@1.15.1
```

**Comment by kolaloko** [comment]
@shimaore You're right, I modified the @session in one helper. Now there is no error. Thank you.

Can you give me an advice how to access the session? @session is undefined in socket handler. I'm using passport and @use passport.session(). But in @socket is no session, only sessionId.

**Comment by shimaore** [comment]
@kolaloko You need to bind the express and the socket.io sessions client-side; you can do this manually, or use [zappajs-client](https://github.com/zappajs/zappajs-client) to do it. The code for zappajs-client contains [more information about how it's done](https://github.com/zappajs/zappajs-client/blob/master/index.coffee.md#automatically-binding-expressjs-and-socketio).

![overview](https://raw.githubusercontent.com/zappajs/zappajs/6.x/docs/share.png)

**Comment by kolaloko** [comment]
@shimaore Thank you. I'm using passport, passport.socketio for authorization.
Can I bind it like this? It works but I want to be sure.
```
    sessionMidd = session(
        store: @sessionStore
        maxAge: new Date(Date.now() + ttlTime * 1000)
        secret: sessionSecret
        cookie:
            maxAge: ttlTime * 100000
            secure: true
        resave: true
        saveUninitialized: false
        name: sessionName
    )

    @use sessionMidd

    @io.use (socket, next) ->
        sessionMidd(socket.request, socket.request.res, next)
```

**Comment by shimaore** [comment]
The real test if whether you can split Express and Socket.io when you do that. For example have one Node.js process [running with `io:false`](https://github.com/zappajs/zappajs/blob/6.x/examples/share_express.coffee), and another one [serving only `@on`](https://github.com/zappajs/zappajs/blob/6.x/examples/share_socket.coffee), the client connecting to the first one for content and the second one for socket.io.

**Comment by kolaloko** [comment]
@shimaore Thank you for the tip.
